/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/frame.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[0.25, 0.012, 0.015]} position-x={1} position-z={0} castShadow receiveShadow>
      <group rotation={[-Math.PI / 2, 0, 0]} castShadow receiveShadow>
        <group rotation={[Math.PI / 2, 0, 0]} castShadow receiveShadow>
          <group rotation={[0, Math.PI / 2, 0]} castShadow receiveShadow>
            <mesh geometry={nodes.Box046_Frame_0.geometry} material={materials.Frame} castShadow receiveShadow />
            <mesh geometry={nodes['Box046_Material_#25_0'].geometry} material={materials.Material_25} castShadow receiveShadow />
            <mesh geometry={nodes['Box046_Material_#26_0'].geometry} material={materials.Material_26} castShadow receiveShadow />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/frame.gltf')
